### ISSUE TITLE
sesService.region = awsRegion sometimes calls the wrong setter

### ISSUE THREAD

**Issue by plocke** [grails-aws/grails-aws#51]
Using Groovy 2.3.11 and Java 1.7 The aws-java-sdk library introduced a new setter somewhere in 1.9.x for setting region - now there are two, one for a singleton list as a convenience method

 public void setRegion(Region region) throws IllegalArgumentException {
 public final void setRegion(Regions region) {

For whatever reason, perhaps groovy or jdk bug, it tries to call the plural setter with the single object, causing illegalArgumentException.  SOMETIMES.   While not your issue per se, probably something in the operator overloading, so a replacement with sesService.setRegion(awsRegion) is recommended.

**Comment by v1p** [comment]
Yeah very weird. For me it only happens when I set the region to 'us_east_1' (dev zone) while it works perfectly when I set some other zone (production zone)
This is the stacktrace snippet :

```groovy
| Error org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object 'us-east-1' with class 'com.amazonaws.regions.Region' to class 'com.amazonaws.regions.Regions'
| Error         at org.codehaus.groovy.runtime.typehandling.ShortTypeHandling.castToEnum(ShortTypeHandling.java:55)
| Error         at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.castToType(DefaultTypeTransformation.java:212)
| Error         at groovy.lang.MetaClassImpl.setProperty(MetaClassImpl.java:2652)
| Error         at groovy.lang.ExpandoMetaClass.setProperty(ExpandoMetaClass.java:1170)
| Error         at groovy.lang.MetaClassImpl.setProperty(MetaClassImpl.java:3702)
| Error         at org.codehaus.groovy.runtime.InvokerHelper.setProperty(InvokerHelper.java:195)
| Error         at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.setProperty(ScriptBytecodeAdapter.java:482)
| Error         at grails.plugin.aws.ses.SendSesMail.sendSimpleMail(SendSesMail.groovy:195)
| Error         at grails.plugin.aws.ses.SendSesMail$sendSimpleMail$4.callCurrent(Unknown Source)
| Error         at grails.plugin.aws.ses.SendSesMail.send(SendSesMail.groovy:140)
| Error         at grails.plugin.aws.ses.SendSesMail$send$0.call(Unknown Source)
| Error         at grails.plugin.aws.util.MetaClassInjector$_injectSesMethods_closure4_closure5.doCall(MetaClassInjector.groovy:74)

```

Do you accept PRs ? I haven't tested the fix suggested by @plocke , but going to try it.

**Comment by j4y** [comment]
Yes.  If you can come up with a PR that fixes it, i'll release a new version.

**Comment by plocke** [comment]
That is indeed the same stacktrace I am seeing.  If you can reproduce (and fix) reliably @v1p please submit a PR;  I can't seem to.  It varies between compiles for me on the same code.

**Comment by v1p** [comment]
I believe #49 is also related, which might get fixed with the PR

**Comment by j4y** [comment]
I released a new version with this fix.  Thanks!

`:aws:1.9.13.1`

**Comment by v1p** [comment]
Everything is working fine now, no exceptions for any region whatsoever. @plocke : Can you please confirm as well with the latest version of plugin ?

**Comment by plocke** [comment]
Will do at earliest opportunity, likely Friday.

**Comment by plocke** [comment]
Confirmed this has fixed this issue across my dev team, thanks for the quick turnaround.  We love using plugins with active support.

**Comment by plocke** [comment]
Just got bitten by this again when sending raw mail for the first time.  There is another spot where sesService.region is assigned directly, on line 303 of SendSesMail.groovy  - the same fix should solve it

**Comment by v1p** [comment]
There, have pushed a new PR, and ran a thorough check to any stray references to .region. I hope this PR takes care of this issue for good.

**Comment by j4y** [comment]
I released a new version with this fix:
`1.9.13.2`

**Comment by j4y** [comment]
I'm still seeing an exception related to region with 1.9.13.2:
`Invalid property 'region' of bean class [grails.plugin.aws.ses.SendSesMail]: Bean property 'region' is not writable or has an invalid setter method. Does the parameter type of the setter match the return type of the getter?`
